import PageLayout from '@/app/components/PageLayout';

export default function ReportsMonthlyPage() {
  // Monthly summaries will be generated from cross-module data snapshots.
  return (
    <PageLayout>
      <div className="rounded-2xl border border-[var(--border-soft)] bg-[var(--surface-0)] p-6">
        <p className="text-xs font-semibold uppercase tracking-wide text-[var(--text-muted)]">Reports</p>
        <h1 className="mt-2 text-2xl font-semibold text-[var(--text-primary)]">Monthly</h1>
        <p className="mt-3 text-sm text-[var(--text-muted)]">
          Monthly reports are autogenerated when the month closes and update if any underlying data changes.
          These summaries combine data across all app pages.
        </p>
      </div>
    </PageLayout>
  );
}
